secrets:
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt

networks:
  frontend:
    external: true
    name: ${DOCKER_PROXY_NETWORK}
  backend:

services:
  db:
    image: postgres:${POSTGRES_TAG}
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    networks:
      - backend
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - backend

  nextcloud:
    build:
      context: nextcloud
      args:
        NEXTCLOUD_TAG: ${NEXTCLOUD_TAG}
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/var/www/html:/var/www/html:rw
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
      - nextcloud_admin_user
      - nextcloud_admin_password
    networks:
      - frontend
      - backend
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/nextcloud_admin_user
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: ${NGINX_HOST}
      OVERWRITEPROTOCOL: https
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:${NEXTCLOUD_TAG}
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/var/www/html:/var/www/html
    networks:
      - backend
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
