secrets:
  mariadb_password:
    file: ./mariadb_password.txt

services:
  db:
    image: mariadb:${MARIADB_TAG}
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    secrets:
      - mariadb_password
    volumes:
      - ${VOLUME_PATH}/var/lib/mysql:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud

  redis:
    image: redis:alpine
    restart: unless-stopped

  nextcloud:
    build:
      context: nextcloud
      args:
        NEXTCLOUD_TAG: ${NEXTCLOUD_TAG}
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/var/www/html:/var/www/html
    secrets:
      - mariadb_password
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: ${NGINX_HOST}
      OVERWRITEPROTOCOL: https
    depends_on:
      - db
      - redis

  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ${SSL_CERT_PATH}:/etc/ssl/certs/server.cert.pem
      - ${SSL_KEY_PATH}:/etc/ssl/private/server.key.pem
    environment:
      NGINX_HOST: ${NGINX_HOST}
    depends_on:
      - nextcloud
